FROM node:22-alpine AS builder

WORKDIR /app

COPY client/package.json client/pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile

COPY client/ ./

RUN pnpm run build

FROM node:22-alpine

WORKDIR /app
COPY --from=builder /app /app

RUN npm install -g pnpm

EXPOSE 4173
CMD ["pnpm", "run", "preview", "--host", "0.0.0.0"]
