FROM node:22-alpine

RUN apk add --no-cache bash libc6-compat
RUN npm install -g pnpm 

WORKDIR /app

COPY client/package.json client/pnpm-lock.yaml ./
RUN pnpm install

COPY ./client .

CMD [ "pnpm", "run", "dev" ]
