FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY ./server/go.mod ./server/go.sum ./
RUN go mod download

COPY ./server ./

RUN go build -o myapp main.go

FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/myapp .

COPY ./server/migrations ./migrations

EXPOSE 8080

CMD ["./myapp"]
