FROM golang:1.25-alpine

WORKDIR /app

RUN apk update && apk upgrade --no-cache && apk add --no-cache git curl

ENV GO111MODULE=on

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
    | sh -s -- -b $(go env GOPATH)/bin v1.51.2

COPY ./server/go.mod ./server/go.sum ./
RUN go mod download

RUN go install github.com/githubnemo/CompileDaemon@latest

COPY ./server ./

CMD ["CompileDaemon", "-log-prefix=false", "-build=go build -o /tmp/myapp main.go", "-command=/tmp/myapp"]
